/* =======================================================================
   products-data.js — Catálogo completo de productos
   Añade/edita la info de cada producto aquí cuando la tengas disponible.
   ======================================================================= */

window.PRODUCTS_DATA = [
  {
    id: 1,
    title: "Letrero LED Programable en RGB, 1 Cara",
    badge: "",
    tags: ["RGB", "1 Cara", "Interior / Exterior"],
    shortDesc: "Letrero LED programable en RGB con millones de colores, disponible en 1 cara.",
    desc: "Letrero LED programable en RGB con millones de colores, disponible en 1 cara. Disponible en varios tamaños para adaptarse a cualquier espacio. Ideal para publicidad en locales comerciales, escaparates y montras. Programación sencilla mediante USB o WiFi.",
    images: [
      "img/producto-1/img-3.jpg",
      "img/producto-1/img-1.jpg",
      "img/producto-1/img-2.jpg",
      "img/producto-1/img-4.jpg",
      "img/producto-1/img-5.jpg",
      "img/producto-1/img-6.jpg",
      "img/producto-1/img-7.jpg",
      "img/producto-1/img-8.jpg",
      "img/producto-1/img-9.jpg",
      "img/producto-1/img-10.jpg"
    ],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  },
  {
    id: 2,
    title: "Pantalla LED Programable Full Color P10 (Exterior) 1 Cara",
    badge: "",
    tags: ["Full Color", "P10", "Exterior", "1 Cara"],
    shortDesc: "Pantalla LED programable Full Color P10 para exterior, 1 cara.",
    desc: "Pantalla LED programable Full Color P10 para exterior, 1 cara. Alta resolución con pixel pitch P10, resistente a la intemperie IP65. Perfecta para publicidad LED en grandes superficies, estaciones de servicio, centros comerciales y fachadas. Incluye control remoto.",
    images: [],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  },
  {
    id: 3,
    title: "Pantalla LED Programable Full Color P5 (Exterior) 1 Cara",
    badge: "",
    tags: ["Full Color", "P5", "Exterior", "1 Cara"],
    shortDesc: "Pantalla LED programable Full Color P5 para exterior, 1 cara.",
    desc: "Pantalla LED programable Full Color P5 para exterior, 1 cara. Mayor resolución que P10 con pixel pitch P5, ideal para distancias cortas y medias. Imágenes nítidas y colores vivos. Resistente a la intemperie. Incluye control remoto y software de programación.",
    images: [],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  },
  {
    id: 4,
    title: "Letrero LED Programable, 1 Cara",
    badge: "Más vendido",
    tags: ["1 Cara", "Más vendido"],
    shortDesc: "Letrero LED programable de 1 cara, disponible en varios tamaños y colores.",
    desc: "Letrero LED programable de 1 cara, disponible en varios tamaños y colores. Perfecto para negocios que buscan visibilidad con bajo consumo energético. Programación sencilla por USB o WiFi. Incluye soporte y kit de montaje.",
    images: [],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  },
  {
    id: 5,
    title: "Letrero LED Programable, 2 Caras",
    badge: "",
    tags: ["2 Caras"],
    shortDesc: "Letrero LED programable de 2 caras, disponible en varios tamaños y colores.",
    desc: "Letrero LED programable de 2 caras, disponible en varios tamaños y colores. Máxima visibilidad desde ambos lados, ideal para entradas, calles peatonales y espacios con tráfico en dos sentidos. Incluye soporte lateral y kit de montaje.",
    images: [],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  },
  {
    id: 6,
    title: "Pantalla LED Programable Full Color P6 (Exterior) 1 Cara",
    badge: "",
    tags: ["Full Color", "P6", "Exterior", "1 Cara"],
    shortDesc: "Pantalla LED programable Full Color P6 para exterior, 1 cara.",
    desc: "Pantalla LED programable Full Color P6 para exterior, 1 cara. Pixel pitch P6, equilibrio perfecto entre resolución y precio. Resistente a la intemperie IP65, colores vivos y alto brillo. Ideal para carteles publicitarios en exteriores.",
    images: [],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  },
  {
    id: 7,
    title: "Pantalla LED Programable Full Color P5 (Interior) 1 Cara",
    badge: "",
    tags: ["Full Color", "P5", "Interior", "1 Cara"],
    shortDesc: "Pantalla LED programable Full Color P5 para interior, 1 cara.",
    desc: "Pantalla LED programable Full Color P5 para interior, 1 cara. Alta resolución con pixel pitch P5, perfecta para escaparates, stands y puntos de venta interiores. Imágenes y vídeos a todo color con gran nitidez.",
    images: [],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  },
  {
    id: 8,
    title: "Letrero LED Programable para Parking en RGB, 1 Cara",
    badge: "",
    tags: ["RGB", "Parking", "1 Cara"],
    shortDesc: "Letrero LED programable específico para parking, en RGB, 1 cara.",
    desc: "Letrero LED programable específico para parking, en RGB, 1 cara. Disponible en varios tamaños. Muestra mensajes de libre/completo, tarifas y horarios. Alta visibilidad día y noche. Ideal para aparcamientos públicos y privados.",
    images: [],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  },
  {
    id: 9,
    title: "Letrero LED Programable para Autoescuelas en RGB, 1 Cara",
    badge: "",
    tags: ["RGB", "Autoescuelas", "1 Cara"],
    shortDesc: "Letrero LED programable diseñado para autoescuelas, en RGB, 1 cara.",
    desc: "Letrero LED programable diseñado para autoescuelas, en RGB, 1 cara. Muestra horarios de clases, información de matrícula y mensajes promocionales. Alta visibilidad, programación sencilla. Disponible en varios tamaños.",
    images: [],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  },
  {
    id: 10,
    title: "Letrero LED Programable en RGB, 2 Caras",
    badge: "",
    tags: ["RGB", "2 Caras"],
    shortDesc: "Letrero LED programable en RGB, 2 caras. Disponible en varios tamaños.",
    desc: "Letrero LED programable en RGB, 2 caras. Disponible en varios tamaños. Visibilidad doble para mayor impacto publicitario. Millones de colores y efectos. Ideal para negocios en calles con tráfico en ambas direcciones.",
    images: [],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  },
  {
    id: 11,
    title: "Banderola LED Programable Full Color P5 Doble Cara",
    badge: "",
    tags: ["Full Color", "P5", "Doble Cara", "Banderola"],
    shortDesc: "Banderola LED programable Full Color P5 de doble cara, para fachadas o postes.",
    desc: "Banderola LED programable Full Color P5 de doble cara, diseñada para colgar en fachadas o postes. Alta resolución P5 con colores vivos a todo color. Ideal para centros comerciales, calles peatonales y eventos. Resistente al exterior.",
    images: [],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  },
  {
    id: 12,
    title: "Banderola LED Programable Full Color P10 Doble Cara",
    badge: "",
    tags: ["Full Color", "P10", "Doble Cara", "Banderola"],
    shortDesc: "Banderola LED programable Full Color P10 de doble cara.",
    desc: "Banderola LED programable Full Color P10 de doble cara. Pixel pitch P10, ideal para grandes distancias de visualización. Diseñada para colgar en fachadas o postes. Resistente al exterior y de bajo consumo energético.",
    images: [],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  },
  {
    id: 13,
    title: "Cruz LED Programable para Farmacias – Veterinarias – Clínicas, 2 Caras",
    badge: "",
    tags: ["Cruz LED", "Farmacia", "2 Caras"],
    shortDesc: "Cruz LED programable de 2 caras para farmacias, veterinarias y clínicas.",
    desc: "Cruz LED programable de 2 caras para farmacias, veterinarias y clínicas. Gran visibilidad desde ambos lados. Muestra temperatura, hora y mensajes personalizados. Disponible en verde monocor o RGB. Incluye soporte lateral.",
    images: [],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  },
  {
    id: 14,
    title: "Cruz LED Programable en RGB para Farmacias – Veterinarias",
    badge: "",
    tags: ["Cruz LED", "RGB", "Farmacia"],
    shortDesc: "Cruz LED programable en RGB para farmacias, veterinarias y clínicas, 1 cara.",
    desc: "Cruz LED programable en RGB para farmacias, veterinarias y clínicas, 1 cara. Colores a todo color con millones de combinaciones. Muestra temperatura, hora y textos personalizados. Incluye soporte lateral y programación sencilla.",
    images: [],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  },
  {
    id: 15,
    title: "Letrero LED Programable para Gasolineras en RGB, 1 Cara",
    badge: "",
    tags: ["RGB", "Gasolineras", "1 Cara"],
    shortDesc: "Letrero LED programable específico para gasolineras en RGB, 1 cara.",
    desc: "Letrero LED programable específico para gasolineras en RGB, 1 cara. Muestra precios de combustible, ofertas y mensajes promocionales. Alta visibilidad día y noche. Disponible en varios tamaños adaptados a estaciones de servicio.",
    images: [],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  },
  {
    id: 16,
    title: "Letrero LED Programable para Academias en RGB, 1 Cara",
    badge: "",
    tags: ["RGB", "Academias", "1 Cara"],
    shortDesc: "Letrero LED programable para academias e idiomas en RGB, 1 cara.",
    desc: "Letrero LED programable para academias e idiomas en RGB, 1 cara. Muestra horarios, idiomas disponibles, ofertas y matrículas. Alta visibilidad para atraer nuevos alumnos. Disponible en varios tamaños.",
    images: [],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  },
  {
    id: 17,
    title: "Letrero LED Programable para Clínicas en RGB, 2 Caras",
    badge: "",
    tags: ["RGB", "Clínicas", "2 Caras"],
    shortDesc: "Letrero LED programable para clínicas en RGB, 2 caras.",
    desc: "Letrero LED programable para clínicas en RGB, 2 caras. Doble visibilidad para máximo impacto. Muestra servicios, horarios y mensajes de salud. Disponible en varios tamaños. Incluye soporte lateral y software de programación.",
    images: [],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  },
  {
    id: 18,
    title: "Letrero LED Programable para Clínicas en RGB, 1 Cara",
    badge: "",
    tags: ["RGB", "Clínicas", "1 Cara"],
    shortDesc: "Letrero LED programable para clínicas en RGB, 1 cara.",
    desc: "Letrero LED programable para clínicas en RGB, 1 cara. Muestra servicios médicos disponibles, horarios de consulta y mensajes de bienestar. Alta visibilidad y programación sencilla. Disponible en varios tamaños.",
    images: [],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  },
  {
    id: 19,
    title: "Letrero LED Programable para Parking en RGB, 2 Caras",
    badge: "",
    tags: ["RGB", "Parking", "2 Caras"],
    shortDesc: "Letrero LED programable para parking en RGB, 2 caras.",
    desc: "Letrero LED programable para parking en RGB, 2 caras. Visibilidad desde ambos lados, ideal para entradas de aparcamientos. Muestra información de libre/completo, tarifas y horarios. Disponible en varios tamaños.",
    images: [],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  },
  {
    id: 20,
    title: "Letrero LED Programable para Autoescuelas en RGB, 2 Caras",
    badge: "",
    tags: ["RGB", "Autoescuelas", "2 Caras"],
    shortDesc: "Letrero LED programable para autoescuelas en RGB, 2 caras.",
    desc: "Letrero LED programable para autoescuelas en RGB, 2 caras. Doble visibilidad para máximo impacto. Muestra horarios, precios de matrícula y mensajes promocionales. Disponible en varios tamaños. Incluye soporte lateral.",
    images: [],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  },
  {
    id: 21,
    title: "Letrero LED Programable para Academias en RGB, 2 Caras",
    badge: "",
    tags: ["RGB", "Academias", "2 Caras"],
    shortDesc: "Letrero LED programable para academias en RGB, 2 caras.",
    desc: "Letrero LED programable para academias en RGB, 2 caras. Ideal para academias de idiomas, música, danza y formación. Doble visibilidad. Muestra horarios, idiomas disponibles y ofertas de matrícula. Disponible en varios tamaños.",
    images: [],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  },
  {
    id: 22,
    title: "Letrero LED Programable para Clínicas Dentales en RGB, 2 Caras",
    badge: "",
    tags: ["RGB", "Clínicas Dentales", "2 Caras"],
    shortDesc: "Letrero LED programable para clínicas dentales en RGB, 2 caras.",
    desc: "Letrero LED programable para clínicas dentales en RGB, 2 caras. Muestra servicios de odontología, horarios de cita y mensajes de salud dental. Doble visibilidad. Diseño compatible con imagen corporativa de clínicas.",
    images: [],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  },
  {
    id: 23,
    title: "Letrero LED Programable para Bares – Restaurantes – Cafeterías en RGB, 1 Cara",
    badge: "",
    tags: ["RGB", "Hostelería", "1 Cara"],
    shortDesc: "Letrero LED programable para bares, restaurantes y cafeterías en RGB, 1 cara.",
    desc: "Letrero LED programable para bares, restaurantes y cafeterías en RGB, 1 cara. Muestra menús del día, promociones especiales, horarios y eventos. Alta visibilidad para atraer clientes. Disponible en varios tamaños.",
    images: [],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  },
  {
    id: 24,
    title: "Letrero LED Programable para Bares – Restaurantes – Cafeterías en RGB, 2 Caras",
    badge: "",
    tags: ["RGB", "Hostelería", "2 Caras"],
    shortDesc: "Letrero LED programable para bares, restaurantes y cafeterías en RGB, 2 caras.",
    desc: "Letrero LED programable para bares, restaurantes y cafeterías en RGB, 2 caras. Mayor visibilidad desde dos ángulos. Muestra menús del día, ofertas especiales y eventos. Ideal para terrazas y locales con acceso por dos calles.",
    images: [],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  },
  {
    id: 25,
    title: "Letrero LED Programable para Hoteles en RGB, 1 Cara",
    badge: "",
    tags: ["RGB", "Hoteles", "1 Cara"],
    shortDesc: "Letrero LED programable para hoteles en RGB, 1 cara.",
    desc: "Letrero LED programable para hoteles en RGB, 1 cara. Muestra disponibilidad de habitaciones, eventos, restauración y bienvenida personalizada. Alta visibilidad. Disponible en varios tamaños. Perfecto para la señalización exterior de hoteles.",
    images: [],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  },
  {
    id: 26,
    title: "Letrero LED Programable para Hoteles en RGB, 2 Caras",
    badge: "",
    tags: ["RGB", "Hoteles", "2 Caras"],
    shortDesc: "Letrero LED programable para hoteles en RGB, 2 caras.",
    desc: "Letrero LED programable para hoteles en RGB, 2 caras. Doble visibilidad para señalización exterior completa. Muestra disponibilidad de habitaciones, servicios del hotel, eventos y mensajes de bienvenida. Disponible en varios tamaños.",
    images: [],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  },
  {
    id: 27,
    title: "Letreros LED Programable para Discotecas – Pub en RGB, 1 Cara",
    badge: "",
    tags: ["RGB", "Ocio Nocturno", "1 Cara"],
    shortDesc: "Letrero LED programable para discotecas y pubs en RGB, 1 cara.",
    desc: "Letrero LED programable para discotecas y pubs en RGB, 1 cara. Impacto visual máximo con animaciones y colores vivos. Muestra nombre del local, eventos, DJs y promociones. Disponible en varios tamaños para fachadas y escaparates.",
    images: [],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  },
  {
    id: 28,
    title: "Letreros LED Programable para Discotecas – Pub en RGB, 2 Caras",
    badge: "",
    tags: ["RGB", "Ocio Nocturno", "2 Caras"],
    shortDesc: "Letrero LED programable para discotecas y pubs en RGB, 2 caras.",
    desc: "Letrero LED programable para discotecas y pubs en RGB, 2 caras. Máxima visibilidad desde ambos lados. Impacto visual con colores y animaciones. Perfecto para festivales, eventos y locales de ocio nocturno. Disponible en varios tamaños.",
    images: [],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  },
  {
    id: 29,
    title: "Letrero LED Programable Cronómetro Digital en RGB, 1 Cara",
    badge: "",
    tags: ["RGB", "Cronómetro", "1 Cara"],
    shortDesc: "Letrero LED programable con función de cronómetro digital en RGB, 1 cara.",
    desc: "Letrero LED programable con función de cronómetro digital en RGB, 1 cara. Muestra cuenta atrás, cuenta progresiva, hora en tiempo real y mensajes personalizados. Ideal para gimnasios, competiciones deportivas y eventos. Disponible en varios tamaños.",
    images: [],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  },
  {
    id: 30,
    title: "Letrero LED Programable Cronómetro Digital, 2 Caras",
    badge: "",
    tags: ["Cronómetro", "2 Caras"],
    shortDesc: "Letrero LED programable con función de cronómetro digital, 2 caras.",
    desc: "Letrero LED programable con función de cronómetro digital, 2 caras. Doble visibilidad. Cuenta atrás, cuenta progresiva y hora en tiempo real. Ideal para eventos deportivos, competiciones y espacios públicos con mucho flujo de personas.",
    images: [],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  },
  {
    id: 31,
    title: "Letrero LED Programable para Estancos en RGB, 1 Cara",
    badge: "",
    tags: ["RGB", "Estancos", "1 Cara"],
    shortDesc: "Letrero LED programable para estancos en RGB, 1 cara.",
    desc: "Letrero LED programable para estancos en RGB, 1 cara. Muestra precios de tabaco, loterías, servicios y promociones especiales. Alta visibilidad para atraer clientes. Disponible en varios tamaños adaptados a establecimientos estancos.",
    images: [],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  },
  {
    id: 32,
    title: "Letrero LED Programable para Estancos en RGB, 2 Caras",
    badge: "",
    tags: ["RGB", "Estancos", "2 Caras"],
    shortDesc: "Letrero LED programable para estancos en RGB, 2 caras.",
    desc: "Letrero LED programable para estancos en RGB, 2 caras. Doble visibilidad para máximo impacto. Muestra precios de tabaco, loterías y servicios. Disponible en varios tamaños. Ideal para estancos en zonas peatonales y esquinas.",
    images: [],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  },
  {
    id: 33,
    title: "Letrero LED Programable para el Control de Acceso RGB, 1 Cara",
    badge: "",
    tags: ["RGB", "Control de Acceso", "1 Cara"],
    shortDesc: "Letrero LED programable para control de acceso en RGB, 1 cara.",
    desc: "Letrero LED programable para control de acceso en RGB, 1 cara. Muestra mensajes de PASE / ESPERE / STOP con colores diferenciados. Ideal para parkings, hospitales, supermercados y cualquier espacio con control de aforo. Programación sencilla e inmediata.",
    images: [],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  },
  {
    id: 34,
    title: "Letrero LED Programable para el Control de Acceso Rojo-Verde, 1 Cara",
    badge: "",
    tags: ["Rojo-Verde", "Control de Acceso", "1 Cara"],
    shortDesc: "Letrero LED programable para control de acceso en rojo y verde, 1 cara.",
    desc: "Letrero LED programable para control de acceso en rojo y verde, 1 cara. Sistema sencillo con dos colores para PASE (verde) y STOP (rojo). Ideal para controlar el flujo de personas en accesos, consultas y espacios con aforo limitado.",
    images: [],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  },
  {
    id: 35,
    title: "Cruz LED Programable R5 para Farmacias – Veterinarias",
    badge: "",
    tags: ["Cruz LED", "R5", "Farmacia"],
    shortDesc: "Cruz LED programable R5 de alta resolución para farmacias y veterinarias.",
    desc: "Cruz LED programable R5 de alta resolución para farmacias y veterinarias. Pixel pitch R5, imágenes más nítidas y detalladas. Muestra temperatura, hora, mensajes y animaciones. Incluye soporte lateral. Alta visibilidad tanto de día como de noche.",
    images: [],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  },
  {
    id: 36,
    title: "Letrero LED Programable para Clínicas en RGB, 1 Cara",
    badge: "",
    tags: ["RGB", "Clínicas", "1 Cara"],
    shortDesc: "Letrero LED programable para clínicas en RGB, 1 cara.",
    desc: "Letrero LED programable para clínicas en RGB, 1 cara. Muestra especialidades médicas disponibles, horarios de consulta, avisos y mensajes de salud. Colores vivos y alta visibilidad. Disponible en varios tamaños.",
    images: [],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  },
  {
    id: 37,
    title: "Sonda de Temperatura",
    badge: "",
    price: "30,00 €",
    tags: ["Accesorio"],
    shortDesc: "Muestre la temperatura añadiendo la sonda a su compra.",
    desc: "Muestre la temperatura añadiendo la sonda a su compra. Podrá mostrar en su pantalla la temperatura actual. Nosotros instalamos la sonda dentro de su letrero, usted solo tiene que configurar la programación ¡Y es muy fácil!",
    images: [],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  },
  {
    id: 38,
    title: "Programación por WiFi",
    badge: "",
    price: "50,00 €",
    tags: ["Accesorio"],
    shortDesc: "Programa tu pantalla electrónica en la distancia con ordenador o móvil.",
    desc: "Además de la programación por defecto con memoria USB... ¿Quieres programar tu pantalla electrónica en la distancia con ordenador o móvil? Añade la tarjeta WiFi a tu pedido para poder disfrutar de ella.",
    images: [],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  },
  {
    id: 39,
    title: "Fuente de Alimentación 12/24 V",
    badge: "",
    price: "0,00 €",
    tags: ["Accesorio"],
    shortDesc: "Fuente de alimentación para conectar tu letrero a baterías o vehículos.",
    desc: "¿Quieres alimentar tu letrero programable con 12/24 voltios? Esta es tu fuente de alimentación, para conectar en baterías, vehículos, etc.",
    images: [],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  },
  {
    id: 40,
    title: "Soporte para Banderola",
    badge: "",
    price: "44,99 €",
    tags: ["Accesorio", "Soporte"],
    shortDesc: "La mejor forma de colocar tu banderola LED programable perpendicular a la pared.",
    desc: "La mejor forma de colocar tu banderola LED programable perpendicular a la pared. *Añade este producto a tu carrito si tu compra no lo incluye.",
    images: [],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  },
  {
    id: 41,
    title: "Soportes Traseros (2U)",
    badge: "",
    price: "44,99 €",
    tags: ["Accesorio", "Soporte"],
    shortDesc: "Los mejores anclajes para colocar tu letrero LED programable pegado a la pared.",
    desc: "Los mejores anclajes para colocar tu letrero LED programable pegado a la pared, tanto en exterior como en interior. Hacen que la instalación de nuestros carteles sea muy sencilla.",
    images: [],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  },
  {
    id: 42,
    title: "Kit de Suspensión para Colgado en Interior",
    badge: "",
    price: "14,99 €",
    tags: ["Accesorio", "Soporte"],
    shortDesc: "La mejor forma de colocar tu pantalla LED programable colgada en interior.",
    desc: "La mejor forma de colocar tu pantalla LED programable colgada en interior. Gracias a este kit, colocar tu pantalla en el interior es muy fácil. Añade este producto si es así como quieres colocar tu cartel publicitario.",
    images: [],
    specs: [],
    sizes: [],
    features: [],
    extra: null
  }
];
